### PR TITLE
Fix error in readme

### PR DESCRIPTION
**Pull request by milesrout**
[Review on Reviewable](https://reviewable.io/reviews/galaxy-team/jupiter/10)

### CODE REVIEW

**Comment by milesrout** [comment]
@ThatOtherPerson

---

---

<sup>**[README.md, line 8 [r1]](https://reviewable.io:443/reviews/galaxy-team/jupiter/10#-JlsbPEiLzaPwuWe5axC)** ([raw file](https://github.com/galaxy-team/jupiter/blob/5f43216d64af959f9914f31ae5500616225386ea/README.md#L8)):</sup>
are we still using both of these?

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/galaxy-team/jupiter/10)

**Comment by cassiebeckley** [comment]
@milesrout It looks like we're using them for the parser: https://github.com/galaxy-team/jupiter/tree/develop/src/lib/rl_parser.

**Comment by Mause** [comment]
Huh, whilst we're all here together again, however briefly, do either of you want http://galaxy-team.net to continue existing? The domain needs to be renewed in the next couple of days, and I'm doubting whether it's worth it

**Comment by milesrout** [comment]
I don't see any great need for it. If one of us finds the free time and
inclination to do more work on galaxy in the future we can always reacquire
it, it doesn't seem like something that's going to be immediately snapped
up lol.

**Comment by milesrout** [comment]
[See here](http://galaxy.sh/)

**Pull request merged**
