### PR TITLE
Preliminary jupiter implementation

### PR DESCRIPTION
**Pull request by Mause**
Erm, feel free to review, but kinda expansive...

Less so without the custom parser and lexer though

### CODE REVIEW

**Comment by cassiebeckley** [comment]
Wow.

**Comment by Mause** [comment]
What? :P

**Comment by Mause** [comment]
Without the custom parser and lexer, it's really not that much code

**Comment by Mause** [comment]
Though rather than being a preliminary implementation, it's more of the supporting architecture for the assembler itself, as most of the meat is yet to be implemented

**Comment by milesrout** [comment]
I think he just meant the number of commits.

**Comment by Mause** [comment]
In which case I would have to agree :P

**Pull request merged**
